In [47]:
import pandas as pd
import numpy as np

###FIRST DATASET

In [120]:
data = pd.read_csv("/content/Data-cleaning-for-beginners-using-pandas.csv")
data

    Index   Age      Salary  Rating       Location  Established Easy Apply
0       0  44.0   $44k-$99k     5.4       India,In         1999       TRUE
1       1  66.0   $55k-$66k     3.5    New York,Ny         2002       TRUE
2       2   NaN   $77k-$89k    -1.0    New York,Ny           -1         -1
3       3  64.0   $44k-$99k     4.4       India In         1988         -1
4       4  25.0   $44k-$99k     6.4  Australia Aus         2002         -1
5       5  44.0   $77k-$89k     1.4       India,In         1999       TRUE
6       6  21.0   $44k-$99k     0.0    New York,Ny           -1         -1
7       7  44.0   $44k-$99k    -1.0  Australia Aus           -1         -1
8       8  35.0   $44k-$99k     5.4    New York,Ny           -1         -1
9       9  22.0   $44k-$99k     7.7       India,In           -1       TRUE
10     10  55.0   $10k-$49k     5.4       India,In         2008       TRUE
11     11  44.0   $10k-$49k     6.7       India,In         2009         -1
12     12   NaN   $44k-$99k     0.0       India,In         1999         -1
13     13  25.0   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14     14  66.0   $44k-$99k     4.0  Australia Aus         2020       TRUE
15     15  44.0  $88k-$101k     3.0  Australia Aus         1999         -1
16     16  19.0   $19k-$40k     4.5       India,In         1984         -1
17     17   NaN   $44k-$99k     5.3    New York,Ny         1943       TRUE
18     18  35.0   $44k-$99k     6.7    New York,Ny         1954       TRUE
19     19  32.0   $44k-$99k     3.3    New York,Ny         1955       TRUE
20     20   NaN   $44k-$99k     5.7    New York,Ny         1944       TRUE
21     21  35.0   $44k-$99k     5.0    New York,Ny         1946         -1
22     22  19.0   $55k-$66k     7.8    New York,Ny         1988       TRUE
23     23   NaN   $44k-$99k     2.4    New York,Ny         1999       TRUE
24     24  13.0   $44k-$99k    -1.0    New York,Ny         1987         -1
25     25  55.0   $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN   $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0   $44k-$99k     5.4       India,In         1935         -1
28     28   NaN   $39k-$88k     3.4  Australia Aus         1932         -1

AGE COLUMN

In [121]:
avg_age = data['Age'].mean()
data['Age']=data.Age.fillna(avg_age)
data['Age']=data.Age.round(decimals=1)

In [122]:
data['Age']=data['Age'].astype('int64')
data

    Index  Age      Salary  Rating       Location  Established Easy Apply
0       0   44   $44k-$99k     5.4       India,In         1999       TRUE
1       1   66   $55k-$66k     3.5    New York,Ny         2002       TRUE
2       2   39   $77k-$89k    -1.0    New York,Ny           -1         -1
3       3   64   $44k-$99k     4.4       India In         1988         -1
4       4   25   $44k-$99k     6.4  Australia Aus         2002         -1
5       5   44   $77k-$89k     1.4       India,In         1999       TRUE
6       6   21   $44k-$99k     0.0    New York,Ny           -1         -1
7       7   44   $44k-$99k    -1.0  Australia Aus           -1         -1
8       8   35   $44k-$99k     5.4    New York,Ny           -1         -1
9       9   22   $44k-$99k     7.7       India,In           -1       TRUE
10     10   55   $10k-$49k     5.4       India,In         2008       TRUE
11     11   44   $10k-$49k     6.7       India,In         2009         -1
12     12   39   $44k-$99k     0.0       India,In         1999         -1
13     13   25   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14     14   66   $44k-$99k     4.0  Australia Aus         2020       TRUE
15     15   44  $88k-$101k     3.0  Australia Aus         1999         -1
16     16   19   $19k-$40k     4.5       India,In         1984         -1
17     17   39   $44k-$99k     5.3    New York,Ny         1943       TRUE
18     18   35   $44k-$99k     6.7    New York,Ny         1954       TRUE
19     19   32   $44k-$99k     3.3    New York,Ny         1955       TRUE
20     20   39   $44k-$99k     5.7    New York,Ny         1944       TRUE
21     21   35   $44k-$99k     5.0    New York,Ny         1946         -1
22     22   19   $55k-$66k     7.8    New York,Ny         1988       TRUE
23     23   39   $44k-$99k     2.4    New York,Ny         1999       TRUE
24     24   13   $44k-$99k    -1.0    New York,Ny         1987         -1
25     25   55   $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   39   $55k-$66k     NaN       India,In         1934       TRUE
27     27   52   $44k-$99k     5.4       India,In         1935         -1
28     28   39   $39k-$88k     3.4  Australia Aus         1932         -1

SALARY COLUMN

In [123]:
data['Salary']= data['Salary'].str.replace("$","")
data['Salary']= data['Salary'].str.replace("k","000")
data

<ipython-input-123-b0c82c9d19c2>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['Salary']= data['Salary'].str.replace("$","")

    Index  Age        Salary  Rating       Location  Established Easy Apply
0       0   44   44000-99000     5.4       India,In         1999       TRUE
1       1   66   55000-66000     3.5    New York,Ny         2002       TRUE
2       2   39   77000-89000    -1.0    New York,Ny           -1         -1
3       3   64   44000-99000     4.4       India In         1988         -1
4       4   25   44000-99000     6.4  Australia Aus         2002         -1
5       5   44   77000-89000     1.4       India,In         1999       TRUE
6       6   21   44000-99000     0.0    New York,Ny           -1         -1
7       7   44   44000-99000    -1.0  Australia Aus           -1         -1
8       8   35   44000-99000     5.4    New York,Ny           -1         -1
9       9   22   44000-99000     7.7       India,In           -1       TRUE
10     10   55   10000-49000     5.4       India,In         2008       TRUE
11     11   44   10000-49000     6.7       India,In         2009         -1
12     12   39   44000-99000     0.0       India,In         1999         -1
13     13   25   44000-99000    -1.0  Australia Aus         2019       TRUE
14     14   66   44000-99000     4.0  Australia Aus         2020       TRUE
15     15   44  88000-101000     3.0  Australia Aus         1999         -1
16     16   19   19000-40000     4.5       India,In         1984         -1
17     17   39   44000-99000     5.3    New York,Ny         1943       TRUE
18     18   35   44000-99000     6.7    New York,Ny         1954       TRUE
19     19   32   44000-99000     3.3    New York,Ny         1955       TRUE
20     20   39   44000-99000     5.7    New York,Ny         1944       TRUE
21     21   35   44000-99000     5.0    New York,Ny         1946         -1
22     22   19   55000-66000     7.8    New York,Ny         1988       TRUE
23     23   39   44000-99000     2.4    New York,Ny         1999       TRUE
24     24   13   44000-99000    -1.0    New York,Ny         1987         -1
25     25   55   44000-99000     0.0  Australia Aus         1980       TRUE
26     26   39   55000-66000     NaN       India,In         1934       TRUE
27     27   52   44000-99000     5.4       India,In         1935         -1
28     28   39   39000-88000     3.4  Australia Aus         1932         -1

RATING COLUMN

In [124]:
avg_rating=data['Rating'].mean()
data['Rating']=data['Rating'].fillna(avg_rating)
data['Rating']=data.Rating.round(decimals=1)
data

    Index  Age        Salary  Rating       Location  Established Easy Apply
0       0   44   44000-99000     5.4       India,In         1999       TRUE
1       1   66   55000-66000     3.5    New York,Ny         2002       TRUE
2       2   39   77000-89000    -1.0    New York,Ny           -1         -1
3       3   64   44000-99000     4.4       India In         1988         -1
4       4   25   44000-99000     6.4  Australia Aus         2002         -1
5       5   44   77000-89000     1.4       India,In         1999       TRUE
6       6   21   44000-99000     0.0    New York,Ny           -1         -1
7       7   44   44000-99000    -1.0  Australia Aus           -1         -1
8       8   35   44000-99000     5.4    New York,Ny           -1         -1
9       9   22   44000-99000     7.7       India,In           -1       TRUE
10     10   55   10000-49000     5.4       India,In         2008       TRUE
11     11   44   10000-49000     6.7       India,In         2009         -1
12     12   39   44000-99000     0.0       India,In         1999         -1
13     13   25   44000-99000    -1.0  Australia Aus         2019       TRUE
14     14   66   44000-99000     4.0  Australia Aus         2020       TRUE
15     15   44  88000-101000     3.0  Australia Aus         1999         -1
16     16   19   19000-40000     4.5       India,In         1984         -1
17     17   39   44000-99000     5.3    New York,Ny         1943       TRUE
18     18   35   44000-99000     6.7    New York,Ny         1954       TRUE
19     19   32   44000-99000     3.3    New York,Ny         1955       TRUE
20     20   39   44000-99000     5.7    New York,Ny         1944       TRUE
21     21   35   44000-99000     5.0    New York,Ny         1946         -1
22     22   19   55000-66000     7.8    New York,Ny         1988       TRUE
23     23   39   44000-99000     2.4    New York,Ny         1999       TRUE
24     24   13   44000-99000    -1.0    New York,Ny         1987         -1
25     25   55   44000-99000     0.0  Australia Aus         1980       TRUE
26     26   39   55000-66000     3.5       India,In         1934       TRUE
27     27   52   44000-99000     5.4       India,In         1935         -1
28     28   39   39000-88000     3.4  Australia Aus         1932         -1

In [125]:
data['Rating']=data['Rating'].replace(-1,1)
data.head()

   Index  Age       Salary  Rating       Location  Established Easy Apply
0      0   44  44000-99000     5.4       India,In         1999       TRUE
1      1   66  55000-66000     3.5    New York,Ny         2002       TRUE
2      2   39  77000-89000     1.0    New York,Ny           -1         -1
3      3   64  44000-99000     4.4       India In         1988         -1
4      4   25  44000-99000     6.4  Australia Aus         2002         -1

LOCATION COLUMN

In [126]:
data['Location']= data['Location'].replace({"India,In" : "India" ,"India In": "India", "New York,Ny": "New York", "Australia Aus":"Australia"})
data.head()

   Index  Age       Salary  Rating   Location  Established Easy Apply
0      0   44  44000-99000     5.4      India         1999       TRUE
1      1   66  55000-66000     3.5   New York         2002       TRUE
2      2   39  77000-89000     1.0   New York           -1         -1
3      3   64  44000-99000     4.4      India         1988         -1
4      4   25  44000-99000     6.4  Australia         2002         -1

ESTABLISHED COLUMN

In [127]:
data['Established'] = data['Established'].replace(-1, np.nan)

In [128]:
established = data['Established'].mean()
data['Established']=data['Established'].fillna(established)
data['Established']=data.Established.round(decimals=1)
data['Established']=data['Established'].astype('int64')
data

    Index  Age        Salary  Rating   Location  Established Easy Apply
0       0   44   44000-99000     5.4      India         1999       TRUE
1       1   66   55000-66000     3.5   New York         2002       TRUE
2       2   39   77000-89000     1.0   New York         1980         -1
3       3   64   44000-99000     4.4      India         1988         -1
4       4   25   44000-99000     6.4  Australia         2002         -1
5       5   44   77000-89000     1.4      India         1999       TRUE
6       6   21   44000-99000     0.0   New York         1980         -1
7       7   44   44000-99000     1.0  Australia         1980         -1
8       8   35   44000-99000     5.4   New York         1980         -1
9       9   22   44000-99000     7.7      India         1980       TRUE
10     10   55   10000-49000     5.4      India         2008       TRUE
11     11   44   10000-49000     6.7      India         2009         -1
12     12   39   44000-99000     0.0      India         1999         -1
13     13   25   44000-99000     1.0  Australia         2019       TRUE
14     14   66   44000-99000     4.0  Australia         2020       TRUE
15     15   44  88000-101000     3.0  Australia         1999         -1
16     16   19   19000-40000     4.5      India         1984         -1
17     17   39   44000-99000     5.3   New York         1943       TRUE
18     18   35   44000-99000     6.7   New York         1954       TRUE
19     19   32   44000-99000     3.3   New York         1955       TRUE
20     20   39   44000-99000     5.7   New York         1944       TRUE
21     21   35   44000-99000     5.0   New York         1946         -1
22     22   19   55000-66000     7.8   New York         1988       TRUE
23     23   39   44000-99000     2.4   New York         1999       TRUE
24     24   13   44000-99000     1.0   New York         1987         -1
25     25   55   44000-99000     0.0  Australia         1980       TRUE
26     26   39   55000-66000     3.5      India         1934       TRUE
27     27   52   44000-99000     5.4      India         1935         -1
28     28   39   39000-88000     3.4  Australia         1932         -1

EASY APPLY COLUMN

In [129]:
data['Easy Apply']= data['Easy Apply'].replace("-1","FALSE")
data

    Index  Age        Salary  Rating   Location  Established Easy Apply
0       0   44   44000-99000     5.4      India         1999       TRUE
1       1   66   55000-66000     3.5   New York         2002       TRUE
2       2   39   77000-89000     1.0   New York         1980      FALSE
3       3   64   44000-99000     4.4      India         1988      FALSE
4       4   25   44000-99000     6.4  Australia         2002      FALSE
5       5   44   77000-89000     1.4      India         1999       TRUE
6       6   21   44000-99000     0.0   New York         1980      FALSE
7       7   44   44000-99000     1.0  Australia         1980      FALSE
8       8   35   44000-99000     5.4   New York         1980      FALSE
9       9   22   44000-99000     7.7      India         1980       TRUE
10     10   55   10000-49000     5.4      India         2008       TRUE
11     11   44   10000-49000     6.7      India         2009      FALSE
12     12   39   44000-99000     0.0      India         1999      FALSE
13     13   25   44000-99000     1.0  Australia         2019       TRUE
14     14   66   44000-99000     4.0  Australia         2020       TRUE
15     15   44  88000-101000     3.0  Australia         1999      FALSE
16     16   19   19000-40000     4.5      India         1984      FALSE
17     17   39   44000-99000     5.3   New York         1943       TRUE
18     18   35   44000-99000     6.7   New York         1954       TRUE
19     19   32   44000-99000     3.3   New York         1955       TRUE
20     20   39   44000-99000     5.7   New York         1944       TRUE
21     21   35   44000-99000     5.0   New York         1946      FALSE
22     22   19   55000-66000     7.8   New York         1988       TRUE
23     23   39   44000-99000     2.4   New York         1999       TRUE
24     24   13   44000-99000     1.0   New York         1987      FALSE
25     25   55   44000-99000     0.0  Australia         1980       TRUE
26     26   39   55000-66000     3.5      India         1934       TRUE
27     27   52   44000-99000     5.4      India         1935      FALSE
28     28   39   39000-88000     3.4  Australia         1932      FALSE

In [130]:
data['Easy Apply'] = data['Easy Apply'].astype(bool)

DATA TYPE

In [131]:
data.dtypes

Index            int64
Age              int64
Salary          object
Rating         float64
Location        object
Established      int64
Easy Apply        bool
dtype: object

**DATA AFTER CLEANING**

In [132]:
data

    Index  Age        Salary  Rating   Location  Established  Easy Apply
0       0   44   44000-99000     5.4      India         1999        True
1       1   66   55000-66000     3.5   New York         2002        True
2       2   39   77000-89000     1.0   New York         1980        True
3       3   64   44000-99000     4.4      India         1988        True
4       4   25   44000-99000     6.4  Australia         2002        True
5       5   44   77000-89000     1.4      India         1999        True
6       6   21   44000-99000     0.0   New York         1980        True
7       7   44   44000-99000     1.0  Australia         1980        True
8       8   35   44000-99000     5.4   New York         1980        True
9       9   22   44000-99000     7.7      India         1980        True
10     10   55   10000-49000     5.4      India         2008        True
11     11   44   10000-49000     6.7      India         2009        True
12     12   39   44000-99000     0.0      India         1999        True
13     13   25   44000-99000     1.0  Australia         2019        True
14     14   66   44000-99000     4.0  Australia         2020        True
15     15   44  88000-101000     3.0  Australia         1999        True
16     16   19   19000-40000     4.5      India         1984        True
17     17   39   44000-99000     5.3   New York         1943        True
18     18   35   44000-99000     6.7   New York         1954        True
19     19   32   44000-99000     3.3   New York         1955        True
20     20   39   44000-99000     5.7   New York         1944        True
21     21   35   44000-99000     5.0   New York         1946        True
22     22   19   55000-66000     7.8   New York         1988        True
23     23   39   44000-99000     2.4   New York         1999        True
24     24   13   44000-99000     1.0   New York         1987        True
25     25   55   44000-99000     0.0  Australia         1980        True
26     26   39   55000-66000     3.5      India         1934        True
27     27   52   44000-99000     5.4      India         1935        True
28     28   39   39000-88000     3.4  Australia         1932        True

##SECOND DATASET

In [133]:
df = pd.read_csv("/content/chipotle.tsv",sep='\t')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [134]:
df.isna().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [135]:
df['choice_description']=df['choice_description'].fillna('None')
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,None,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [136]:
df.isna().sum()

order_id              0
quantity              0
item_name             0
choice_description    0
item_price            0
dtype: int64

In [150]:
df['item_price'] = df['item_price'].replace('$','')
df['item_price'] = df['item_price'].astype(int)
df.head()

,order_id,quantity,item_name,choice_description,item_price,total_price_calculated
0,1,1,Chips and Fresh Tomato Salsa,None,2,2
1,1,1,Izze,Clementine,3,3
2,1,1,Nantucket Nectar,Apple,3,3
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,2,2
4,2,2,Chicken Bowl,"Tomatillo-Red Chili Salsa (Hot), Black Beans...",16,32

In [139]:
df['choice_description']=df['choice_description'].str.replace("[" ," ")
df['choice_description']=df['choice_description'].str.replace("]" ," ")
df['choice_description']

<ipython-input-139-ac61631be802>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['choice_description']=df['choice_description'].str.replace("[" ," ")
<ipython-input-139-ac61631be802>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['choice_description']=df['choice_description'].str.replace("]" ," ")

0                                                    None
1                                             Clementine
2                                                  Apple
3                                                    None
4        Tomatillo-Red Chili Salsa (Hot),  Black Beans...
                              ...
4617     Fresh Tomato Salsa,  Rice, Black Beans, Sour ...
4618     Fresh Tomato Salsa,  Rice, Sour Cream, Cheese...
4619     Fresh Tomato Salsa,  Fajita Vegetables, Pinto...
4620     Fresh Tomato Salsa,  Fajita Vegetables, Lettu...
4621     Fresh Tomato Salsa,  Fajita Vegetables, Pinto...
Name: choice_description, Length: 4622, dtype: object

In [141]:
df['choice_description'] =df['choice_description'].astype(str)

In [142]:
df.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     6.934660
std     528.890796     0.410186     4.202828
min       1.000000     1.000000     1.000000
25%     477.250000     1.000000     3.000000
50%     926.000000     1.000000     8.000000
75%    1393.000000     1.000000     9.000000
max    1834.000000    15.000000    44.000000

Quantity-Item Relationship:

In [143]:
quantity_item_relation = df.groupby('item_name')['quantity'].sum().reset_index(name= 'total_quantity')
quantity_item_relation

                                item_name  total_quantity
0                       6 Pack Soft Drink              55
1                           Barbacoa Bowl              66
2                        Barbacoa Burrito              91
3                   Barbacoa Crispy Tacos              12
4                     Barbacoa Salad Bowl              10
5                     Barbacoa Soft Tacos              25
6                           Bottled Water             211
7                                    Bowl               4
8                                 Burrito               6
9                             Canned Soda             126
10                      Canned Soft Drink             351
11                          Carnitas Bowl              71
12                       Carnitas Burrito              60
13                  Carnitas Crispy Tacos               8
14                         Carnitas Salad               1
15                    Carnitas Salad Bowl               6
16                    Carnitas Soft Tacos              40
17                           Chicken Bowl             761
18                        Chicken Burrito             591
19                   Chicken Crispy Tacos              50
20                          Chicken Salad               9
21                     Chicken Salad Bowl             123
22                     Chicken Soft Tacos             120
23                                  Chips             230
24           Chips and Fresh Tomato Salsa             130
25                    Chips and Guacamole             506
26      Chips and Mild Fresh Tomato Salsa               1
27     Chips and Roasted Chili Corn Salsa              23
28     Chips and Roasted Chili-Corn Salsa              18
29  Chips and Tomatillo Green Chili Salsa              45
30    Chips and Tomatillo Red Chili Salsa              50
31  Chips and Tomatillo-Green Chili Salsa              33
32    Chips and Tomatillo-Red Chili Salsa              25
33                           Crispy Tacos               2
34                                   Izze              20
35                       Nantucket Nectar              29
36                                  Salad               2
37                          Side of Chips             110
38                             Steak Bowl             221
39                          Steak Burrito             386
40                     Steak Crispy Tacos              36
41                            Steak Salad               4
42                       Steak Salad Bowl              31
43                       Steak Soft Tacos              56
44                            Veggie Bowl              87
45                         Veggie Burrito              97
46                    Veggie Crispy Tacos               1
47                           Veggie Salad               6
48                      Veggie Salad Bowl              18
49                      Veggie Soft Tacos               8

Quantity-price Relationship:

In [144]:
quantity_item_relation = df.groupby('item_name')['item_price'].sum().reset_index(name= 'total_price')
quantity_item_relation

                                item_name  total_price
0                       6 Pack Soft Drink          330
1                           Barbacoa Bowl          637
2                        Barbacoa Burrito          846
3                   Barbacoa Crispy Tacos          114
4                     Barbacoa Salad Bowl          100
5                     Barbacoa Soft Tacos          239
6                           Bottled Water          238
7                                    Bowl           29
8                                 Burrito           42
9                             Canned Soda          126
10                      Canned Soft Drink          354
11                          Carnitas Bowl          698
12                       Carnitas Burrito          567
13                  Carnitas Crispy Tacos           73
14                         Carnitas Salad            8
15                    Carnitas Salad Bowl           62
16                    Carnitas Soft Tacos          360
17                           Chicken Bowl         6932
18                        Chicken Burrito         5257
19                   Chicken Crispy Tacos          446
20                          Chicken Salad           76
21                     Chicken Salad Bowl         1170
22                     Chicken Soft Tacos         1039
23                                  Chips          459
24           Chips and Fresh Tomato Salsa          280
25                    Chips and Guacamole         1921
26      Chips and Mild Fresh Tomato Salsa            3
27     Chips and Roasted Chili Corn Salsa           47
28     Chips and Roasted Chili-Corn Salsa           36
29  Chips and Tomatillo Green Chili Salsa           92
30    Chips and Tomatillo Red Chili Salsa          102
31  Chips and Tomatillo-Green Chili Salsa           66
32    Chips and Tomatillo-Red Chili Salsa           52
33                           Crispy Tacos           14
34                                   Izze           60
35                       Nantucket Nectar           87
36                                  Salad           14
37                          Side of Chips          117
38                             Steak Bowl         2132
39                          Steak Burrito         3612
40                     Steak Crispy Tacos          336
41                            Steak Salad           32
42                       Steak Salad Bowl          323
43                       Steak Soft Tacos          508
44                            Veggie Bowl          827
45                         Veggie Burrito          889
46                    Veggie Crispy Tacos            8
47                           Veggie Salad           48
48                      Veggie Salad Bowl          174
49                      Veggie Soft Tacos           70

MOST ORDERED ITEMS

In [145]:
most_order=df.sort_values(by="quantity",ascending=False)
most_order.head()

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,None,44
4152,1660,10,Bottled Water,None,15
3887,1559,8,Side of Chips,None,13
3599,1443,7,Bottled Water,None,10
2441,970,5,Bottled Water,None,7

REVENUE OF EACH ITEMS

In [146]:
df['total_price_calculated'] = df['quantity'] * df['item_price']
revenue_each = df[df['total_price_calculated'] != df['item_price']]
revenue_each

,order_id,quantity,item_name,choice_description,item_price,total_price_calculated
4,2,2,Chicken Bowl,"Tomatillo-Red Chili Salsa (Hot), Black Beans...",16,32
18,9,2,Canned Soda,Sprite,2,4
51,23,2,Canned Soda,Mountain Dew,2,4
135,60,2,Chicken Salad Bowl,"Tomatillo Green Chili Salsa, Sour Cream, Che...",22,44
148,67,2,Steak Burrito,"Tomatillo-Red Chili Salsa (Hot), Rice, Chees...",17,34
...,...,...,...,...,...,...
4491,1786,4,Canned Soft Drink,Sprite,5,20
4499,1789,2,Canned Soft Drink,Coke,2,4
4560,1812,2,Canned Soft Drink,Coke,2,4
4561,1813,2,Chicken Salad Bowl,"Fresh Tomato Salsa, Fajita Vegetables, Pinto...",17,34
4582,1822,2,Bottled Water,None,3,6

In [147]:
unique_item_names = df['item_name'].unique()
unique_item_names

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)

In [148]:
df

,order_id,quantity,item_name,choice_description,item_price,total_price_calculated
0,1,1,Chips and Fresh Tomato Salsa,None,2,2
1,1,1,Izze,Clementine,3,3
2,1,1,Nantucket Nectar,Apple,3,3
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,2,2
4,2,2,Chicken Bowl,"Tomatillo-Red Chili Salsa (Hot), Black Beans...",16,32
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"Fresh Tomato Salsa, Rice, Black Beans, Sour ...",11,11
4618,1833,1,Steak Burrito,"Fresh Tomato Salsa, Rice, Sour Cream, Cheese...",11,11
4619,1834,1,Chicken Salad Bowl,"Fresh Tomato Salsa, Fajita Vegetables, Pinto...",11,11
4620,1834,1,Chicken Salad Bowl,"Fresh Tomato Salsa, Fajita Vegetables, Lettu...",8,8
4621,1834,1,Chicken Salad Bowl,"Fresh Tomato Salsa, Fajita Vegetables, Pinto...",8,8